# GoReleaser configuration for sql-proxy
# https://goreleaser.com

version: 2
project_name: sql-proxy

builds:
  - id: sql-proxy
    binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Tag }}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.BuildTime={{.Date}}

snapshot:
  version_template: "snapshot-{{.ShortCommit}}"

archives:
  - id: sql-proxy-archive
    format: binary
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Tag }}'

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  # 'auto' marks as pre-release if tag is pre-release (e.g., v1.0.0-beta1)
  prerelease: auto
